server:
  context-path: /app
  port: 9090
  jsp-servlet:
    init-parameters:
      developlopment: ture
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123
  mvc:
    view:
      prefix: /
      suffix: .jsp
  aop:
    proxy-target-class: false
  http:
    encoding:
      charset: UTF-8
      force: true


mybatis:
  mapper-locations: com/baizhi/work/dao/*Mapper.xml
  type-aliases-package: com.baizhi.work.entity


